name: release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release bp3ui binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the public/ directory
        run: npm run build

      - name: Check folder public
        run: ls -alF public/

      - uses: wangyoucao577/go-release-action@v1.39
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extra_files: LICENSE README.md
